### Importing Packages
At the top of your notebook should have where you import all packages you need for that notebok. It is good practice.

In [14]:
import numpy as np  # yup thats it

In [131]:
# calling the package
np.    # use TAB to see all the commands

SyntaxError: invalid syntax (<ipython-input-131-de1917e3b3bf>, line 2)

### Lists vs Arrays
We saw the power of using lists to do a set of calculations. However we were limited by the types of math functions that lists can perform.

In [3]:
# remember
my_list = [0,1,2,3,4]
my_list + my_list

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

If we wanted the elements of this list to be added we would have to write a loop like this

In [4]:
new_list = []
for i in range(len(my_list)):
    new_list.append(my_list[i]+my_list[i])
    
new_list

[0, 2, 4, 6, 8]

Now that we have imported NumPy we can define a numpy array and show some of the advantages

In [5]:
# lets hard code our list into a numpy array
data = np.array([0,1,2,3,4])  # syntax for creating numpy array
data

array([0, 1, 2, 3, 4])

In [6]:
# here is the syntax for directly converting list to array
data = np.asarray(my_list)
data

array([0, 1, 2, 3, 4])

The main difference and advantage of a numpy array is its ability to do elemtwise mathematical functions

In [7]:
new_data = data + data
new_data  # notice how easy this is compared to the loops with the list

array([0, 2, 4, 6, 8])

In [8]:
# multiplication
print(my_list*3)
data*3

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


array([ 0,  3,  6,  9, 12])

In [9]:
# division
my_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [10]:
data/2

array([0. , 0.5, 1. , 1.5, 2. ])

If we remember our functions from last time we had to loop through the elements however with arrays it is already assumed to do operations elementwise. 

#### PHYSICS EXAMPLE
If we revisit our physical example of finding the force of a ball of mass 5 kg with a variety of different accelerations, we can easily see the advantages of numpy arrays.

In [13]:
# computing using arrays
m_kg = 5 # define mass 
accel_array = np.array([2,4,6,8,10])  # array of accelerations
Force_array = m_kg*accel_array
Force_array

array([10, 20, 30, 40, 50])

We simply define our mass object and then define our array of accelerations. Then, rather than having to write the logic of a for loop in order to do elementwise computing, we could simply multiply our mass by our accel_array and get our Force_array. 

### Using NumPy arrays 
There are a few common shorthand commands for making arrays. Check out these examples.

In [16]:
# array with all zeros
array = np.zeros(15)  # creates 1d array of all zeros of length 15
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
# array with all ones
array = np.ones(15) # 1d array of all ones
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# multidimensional array off all zeros
big_array = np.zeros((3,3))
big_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [36]:
# identity matrix 
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [46]:
# arange is a way to create an array of values from a start to an end
# and with specified intervals
b_array = np.arange(1,101,1)  # (start, end+1, step size)
b_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [51]:
# use arange to have decreasing values
c_array = np.arange(100,1,-1)
c_array

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [47]:
# linspace is a way to create an array of equally spaced values
# over a specified range

vals = np.linspace(1,100,100)  # (lower, upper, number of steps)
vals

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [28]:
# define an array of all the evens from 2 to 50
evens = np.linspace(2,50,25)
evens

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20., 22., 24., 26.,
       28., 30., 32., 34., 36., 38., 40., 42., 44., 46., 48., 50.])

### Random Sampling
NumPy has some tools for generating random samples. Each has its specific usages and advantages. We will investigate a few of these briefly but again visit the NumPy documentation for a complete referrence. 

In [62]:
# you can create arrays with random values inside
a = np.random.rand(1)  # random number from 0-1 
a         # the 1 in the paranthesis is the dimension of array

array([0.97143328])

In [67]:
b = np.random.rand(5,5)
b

array([[0.34386613, 0.30652299, 0.39836722, 0.96869678, 0.10063678],
       [0.12920943, 0.65666496, 0.54865693, 0.49262592, 0.57121173],
       [0.00509514, 0.06355474, 0.41060138, 0.44253352, 0.16670832],
       [0.81430324, 0.08144379, 0.88270939, 0.27918283, 0.47867212],
       [0.69052494, 0.99872096, 0.31062298, 0.24864211, 0.68325373]])

In [66]:
# very similar but this samples from normal distribution
c = np.random.randn(3)
c

array([-1.39382682,  0.14416478,  0.33705438])

In [72]:
# random integers 
d = np.random.randint(3)  # 3 is upper bound
d

2

In [77]:
rand = np.random.randint(1,10, size = 5)  # (low, high, size)
rand

array([8, 6, 1, 6, 6])

In [95]:
# using a seed for repeatable results
np.random.seed(0)
rand_arr = np.random.randn(4,3)
rand_arr

array([[ 1.76405235,  0.40015721,  0.97873798],
       [ 2.2408932 ,  1.86755799, -0.97727788],
       [ 0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351]])

### Common functions for NumPy arrays

In [78]:
# mean of values in an array
np.mean(rand)

5.4

In [79]:
# variance 
np.var(rand)

5.4399999999999995

In [80]:
# standard deviation
np.std(rand)

2.33238075793812

In [81]:
# sum of the values
np.sum(rand)

27

In [92]:
# for matrices that are not 1d, specify axis
v = np.array([[1,2],[3,4]])
print(v)
row_sum = np.sum(v, axis=1)
row_sum

[[1 2]
 [3 4]]


array([3, 7])

In [91]:
col_sum = np.sum(v, axis=0)
print(v)
col_sum

[[1 2]
 [3 4]]


array([4, 6])

In [96]:
# you can find the min and max 
sample = np.random.randn(10)
sample_max = np.max(sample)
sample_min = np.min(sample)
print(sample)
print(sample_max)
print(sample_min)

[ 0.76103773  0.12167502  0.44386323  0.33367433  1.49407907 -0.20515826
  0.3130677  -0.85409574 -2.55298982  0.6536186 ]
1.4940790731576061
-2.5529898158340787


In [98]:
# use argmax and argmin to find the index for min and mx values
print(np.argmax(sample))
np.argmin(sample)  # python indexing starts from 0

4


8

In [109]:
# you can combine commands together
data = np.random.randn(4,4) # create random data
print('data',data)
col_totals = np.sum(data, axis=0)  # total the columns
print('totals',col_totals)
max_col_total = (np.argmax(col_totals),np.max(col_totals))
max_col_total  # 1st output is the index, 2nd is the value for max

data [[ 0.61407937  0.92220667  0.37642553 -1.09940079]
 [ 0.29823817  1.3263859  -0.69456786 -0.14963454]
 [-0.43515355  1.84926373  0.67229476  0.40746184]
 [-0.76991607  0.53924919 -0.67433266  0.03183056]]
totals [-0.29275208  4.63710549 -0.32018023 -0.80974294]


(1, 4.637105488024716)

In [110]:
# heres how to do in 1 line
max_col_tot = (np.argmax(np.sum(data,axis=0)),
               np.max(np.sum(data,axis=0)))
max_col_tot

(1, 4.637105488024716)

### PHYSICS EXAMPLE
Lets say everyday we record the average temperature for an object. We are interested in finding the day where the object had its maximum temperature. We will first generate random data and this use numpy functions to find the answer. 

In [130]:
# generate random velocities (must be positive)
temp_data = 50*np.random.rand(100)
print('time of max temp - ',np.argmax(temp_data)+1, 'days')
print('max temp - ',np.max(temp_data), 'degrees Celsius')

time of max temp -  85 days
max temp -  49.594516457731466 degrees Celsius


In [11]:
# shape gets the dimensions
a = np.array([[1,2,3],[4,5,6],[7,8,9]])  # syntax for 3x3
print(a)
a.shape

[[1 2 3]
 [4 5 6]
 [7 8 9]]


(3, 3)

In [13]:
# len still works
len(a)

3

In [15]:
# you can index through the elements of the array
print(a[0][0])  # first element of first row
print(a[1][1]) # second element of second row
print(a[-1][-1])  # last element second row
print(a[0])  # first row
print(a[0:2])  # first 2 rows
a[:,0:2]  # first 2 columns

1
5
9
[1 2 3]
[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [4, 5],
       [7, 8]])

In [132]:
# merging numpy arrays horizontally
first = np.array([1,2,3])
second = np.array([4,5,6])
frst_scnd = np.hstack((first,second))
frst_scnd

array([1, 2, 3, 4, 5, 6])

In [133]:
# merge vertically
new_arr = np.vstack((first,second))
new_arr

array([[1, 2, 3],
       [4, 5, 6]])

### NumPy Mathematics
Another important aspect of using the NumPy package is its extensive amount of mathematical functions. This could be exponentials, trigonometric functions, square root, etc...

I've included a bunch of examples of using these commands but I strongly recommend visiting the NumPy documentation to see the complete list of commands.

In [19]:
# mathematical constants
print(np.pi)  
print(np.e)
np.inf

3.141592653589793
2.718281828459045


inf

In [27]:
# trig functions
print(np.sin(np.pi/2))  # takes radian values
print(np.cos(np.pi))
np.tan(np.pi)  # approximations

1.0
-1.0


-1.2246467991473532e-16

In [28]:
# radians to degress
np.degrees(np.pi)

180.0

In [29]:
# degrees to radians
np.radians(180.0)

3.141592653589793

In [31]:
np.e  # is the value of e

# exponential functions
np.exp(3)


20.085536923187668

In [83]:
# linear algebra 
a = np.array([[1,2],[2,1]]) # define 3x3 matrix
inv_a = np.linalg.inv(a)  # inverse 
inv_a

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [84]:
# dot product of 2 matrices
np.dot(a, inv_a)

array([[1., 0.],
       [0., 1.]])

In [112]:
# transpose of a matrix
a_matrix = np.array([[1,2],[3,4]])
trans_a = a_matrix.T
print('a')
print(a_matrix)
print('transpose of a')
print(trans_a)

a
[[1 2]
 [3 4]]
transpose of a
[[1 3]
 [2 4]]


In [114]:
# determinant of a matrix
a_det = np.linalg.det(a_matrix)
a_det

-2.0000000000000004

In [116]:
# find the eigenvalues and eigenvectors of a matrix
a_eig = np.linalg.eig(a_matrix)
a_eig  # outputs in form array([eigenvalues]), array([eigenvectors])

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [118]:
# just like np.sum you can mulitply across an array
# determinant = product of eigenvalues
det = np.prod(a_eig[0])  # the first element of a_eig are the eigvalues
det 

-1.9999999999999998

In [119]:
# to show how python approximates
det == a_det

False

In [123]:
round(det) == round(a_det)

True

### Saving and Reading Data Files
This will be brief but I should mention these functions as a part of the NumPy package. We will revisit saving and reading data files later in the course.

In [142]:
# create random array to be saved as datafile
ex_datafile = np.random.randint(0,10,size = (10,10))
ex_datafile 

array([[3, 8, 9, 6, 2, 1, 7, 7, 6, 7],
       [5, 9, 8, 8, 1, 4, 6, 4, 2, 7],
       [8, 5, 7, 9, 9, 6, 9, 9, 3, 9],
       [3, 7, 2, 8, 1, 3, 2, 1, 7, 8],
       [7, 5, 7, 7, 1, 5, 6, 5, 8, 8],
       [1, 5, 2, 9, 5, 1, 8, 1, 7, 8],
       [5, 0, 1, 9, 5, 1, 4, 9, 8, 2],
       [8, 3, 3, 7, 4, 8, 3, 3, 1, 7],
       [5, 5, 7, 7, 3, 2, 1, 2, 9, 5],
       [8, 8, 8, 2, 2, 8, 4, 1, 1, 0]])

In [143]:
# save numpy array as csv
np.savetxt("datafile.csv", ex_datafile, delimiter=",")

In [146]:
# file is saved in current directory 
# to view all the files in the directory use this command
%ls

 Volume in drive C is Windows
 Volume Serial Number is F885-EF5C

 Directory of C:\Users\bobby\Desktop\UB_PYTHON_COURSE\LECTURE_NOTES

06/07/2019  10:46 AM    <DIR>          .
06/07/2019  10:46 AM    <DIR>          ..
06/05/2019  01:05 PM    <DIR>          .ipynb_checkpoints
06/07/2019  10:46 AM             2,510 datafile.csv
06/07/2019  10:46 AM            33,185 INTRO_NumPy.ipynb
06/05/2019  01:51 PM            23,218 INTRO_PYTHON.ipynb
06/05/2019  11:38 AM             3,498 INTRO_PYTHON1_file_control&basic_computing.ipynb
06/05/2019  11:40 AM            10,682 INTRO_PYTHON2_defining_objects.ipynb
06/05/2019  11:46 AM             4,444 INTRO_PYTHON3_lists&for_loops.ipynb
06/05/2019  02:02 PM             9,810 INTRO_PYTHON4_if_statements&functions.ipynb
               7 File(s)         87,347 bytes
               3 Dir(s)  13,316,063,232 bytes free


In [148]:
# to read in files that are saved in the directory
np.loadtxt("datafile.csv", delimiter = ",")

array([[3., 8., 9., 6., 2., 1., 7., 7., 6., 7.],
       [5., 9., 8., 8., 1., 4., 6., 4., 2., 7.],
       [8., 5., 7., 9., 9., 6., 9., 9., 3., 9.],
       [3., 7., 2., 8., 1., 3., 2., 1., 7., 8.],
       [7., 5., 7., 7., 1., 5., 6., 5., 8., 8.],
       [1., 5., 2., 9., 5., 1., 8., 1., 7., 8.],
       [5., 0., 1., 9., 5., 1., 4., 9., 8., 2.],
       [8., 3., 3., 7., 4., 8., 3., 3., 1., 7.],
       [5., 5., 7., 7., 3., 2., 1., 2., 9., 5.],
       [8., 8., 8., 2., 2., 8., 4., 1., 1., 0.]])