In [2]:
import numpy as np  # yup thats it

### NumPy Mathematics
Another important aspect of using the NumPy package is its extensive amount of mathematical functions. This could be exponentials, trigonometric functions, square root, etc...

I've included a bunch of examples of using these commands but I strongly recommend visiting the NumPy documentation to see the complete list of commands.

In [3]:
# mathematical constants
print(np.pi)  
print(np.e)
np.inf #infinity

3.141592653589793
2.718281828459045


inf

In [4]:
# trig functions
print(np.sin(np.pi/2))  # takes radian values
print(np.cos(np.pi))
np.tan(np.pi)  # approximations

1.0
-1.0


-1.2246467991473532e-16

In [5]:
# radians to degress
np.degrees(np.pi)

180.0

In [6]:
# degrees to radians
np.radians(180.0)

3.1415926535897931

In [8]:
print(np.e)  # is the value of e

# exponential functions
np.exp(3)

2.718281828459045


20.085536923187668

In [9]:
# linear algebra 
a = np.array([[1,2],[2,1]]) # define 2x2 matrix
inv_a = np.linalg.inv(a)  # inverse, linalg stands for linear algebra 
inv_a

array([[-0.33333333,  0.66666667],
       [ 0.66666667, -0.33333333]])

In [ ]:
# dot product of 2 matrices
np.dot(a, inv_a)

In [10]:
# transpose of a matrix
a_matrix = np.array([[1,2],[3,4]])
trans_a = a_matrix.T # T stands for transpose
print('a')
print(a_matrix)
print('transpose of a')
print(trans_a)

a
[[1 2]
 [3 4]]
transpose of a
[[1 3]
 [2 4]]


In [11]:
# determinant of a matrix
a_det = np.linalg.det(a_matrix)
a_det

-2.0000000000000004

In [14]:
# find the eigenvalues and eigenvectors of a matrix
a_eig = np.linalg.eig(a_matrix)
a_eig  # outputs in form array([eigenvalues]), array([eigenvectors])

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [15]:
# just like np.sum you can mulitply across an array
# determinant = product of eigenvalues
det = np.prod(a_eig[0])  # the first element of a_eig are the eigvalues
det 

-1.9999999999999998

In [16]:
# to show how python approximates
det == a_det

False

In [17]:
round(det) == round(a_det)

True

### Saving and Reading Data Files
This will be brief but I should mention these functions as a part of the NumPy package. We will revisit saving and reading data files later in the course.

In [18]:
# create random array to be saved as datafile
ex_datafile = np.random.randint(0,10,size = (10,10))
ex_datafile 

array([[0, 2, 0, 1, 6, 0, 1, 9, 8, 3],
       [2, 2, 3, 0, 9, 5, 1, 2, 8, 6],
       [8, 7, 3, 2, 1, 6, 0, 6, 3, 8],
       [9, 2, 5, 6, 5, 2, 0, 0, 5, 5],
       [2, 0, 8, 9, 6, 8, 3, 5, 7, 7],
       [2, 9, 7, 8, 2, 7, 4, 8, 4, 8],
       [0, 7, 2, 6, 5, 2, 4, 0, 2, 2],
       [3, 7, 0, 6, 6, 5, 6, 6, 7, 1],
       [7, 2, 6, 9, 9, 8, 7, 3, 7, 6],
       [6, 6, 0, 4, 2, 5, 3, 8, 4, 9]])

In [19]:
# save numpy array as csv
np.savetxt("datafile.csv", ex_datafile, delimiter=",")

In [20]:
# file is saved in current directory 
# to view all the files in the directory use this command
%ls

datafile.csv
INTRO_NumPy1.ipynb
INTRO_NumPy2.ipynb
INTRO_NumPy3.ipynb
INTRO_NumPy.ipynb
INTRO_PYTHON1_file_control&basic_computing.ipynb
INTRO_PYTHON2_defining_objects.ipynb
INTRO_PYTHON3_lists&for_loops.ipynb
INTRO_PYTHON4_if_statements&functions.ipynb
INTRO_PYTHON.ipynb
Learn_MatPlotLib.ipynb
Practicing Conditional Statements.ipynb
RPS.ipynb
Sample_Project.ipynb
untitled.dio


In [22]:
# to read in files that are saved in the directory
reee = np.loadtxt("datafile.csv", delimiter = ",")