### Importing Packages
At the top of your notebook should have where you import all packages you need for that notebok. It is good practice.

In [2]:
import numpy as np  # yup thats it

In [3]:
# calling the package
np.    # use TAB to see all the commands

SyntaxError: invalid syntax (<ipython-input-3-de1917e3b3bf>, line 2)

### Lists vs Arrays
We saw the power of using lists to do a set of calculations. However we were limited by the types of math functions that lists can perform.

In [4]:
# remember
my_list = [0,1,2,3,4]
my_list + my_list

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]

If we wanted the elements of this list to be added we would have to write a loop like this

In [5]:
new_list = []
for i in range(len(my_list)):
    new_list.append(my_list[i]+my_list[i])
    
new_list

[0, 2, 4, 6, 8]

Now that we have imported NumPy we can define a numpy array and show some of the advantages

In [6]:
# lets hard code our list into a numpy array
data = np.array([0,1,2,3,4])  # syntax for creating numpy array. Inputs should be in a list
data

array([0, 1, 2, 3, 4])

In [7]:
# here is the syntax for directly converting list to array
data = np.asarray(my_list)
data

array([0, 1, 2, 3, 4])

The main difference and advantage of a numpy array is its ability to do element-wise mathematical functions

In [8]:
new_data = data + data
new_data  # notice how easy this is compared to the loops with the list

array([0, 2, 4, 6, 8])

In [9]:
# multiplication
print(my_list*3)
data*3

[0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]


array([ 0,  3,  6,  9, 12])

In [10]:
# division
my_list/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [11]:
data/2

array([ 0. ,  0.5,  1. ,  1.5,  2. ])

If we remember our functions from last time we had to loop through the elements however with arrays it is already assumed to do operations elementwise. 

#### PHYSICS EXAMPLE
If we revisit our physical example of finding the force of a ball of mass 5 kg with a variety of different accelerations, we can easily see the advantages of numpy arrays.

In [12]:
# computing using arrays
m_kg = 5 # define mass 
accel_array = np.array([2,4,6,8,10])  # array of accelerations
Force_array = m_kg*accel_array
Force_array

array([10, 20, 30, 40, 50])

We simply define our mass object and then define our array of accelerations. Then, rather than having to write the logic of a for loop in order to do elementwise computing, we could simply multiply our mass by our accel_array and get our Force_array. 

### Using NumPy arrays 
There are a few common shorthand commands for making arrays. Check out these examples.

In [13]:
# array with all zeros
array = np.zeros(15)  # creates 1d array of all zeros of length 15
array

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.])

In [14]:
# array with all ones
array = np.ones(15) # 1d array of all ones
array

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.])

In [15]:
# multidimensional array off all zeros
big_array = np.zeros((3,3)) #able to print in a defined grid pattern, i.e 3 x 3
big_array

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
# identity matrix 
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [17]:
# arange is a way to create an array of values from a start to an end
# and with specified intervals
b_array = np.arange(1,101,1)  # (start, end+1, step size)
b_array

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [18]:
# use arange to have decreasing values
c_array = np.arange(100,1,-1)
c_array

array([100,  99,  98,  97,  96,  95,  94,  93,  92,  91,  90,  89,  88,
        87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  76,  75,
        74,  73,  72,  71,  70,  69,  68,  67,  66,  65,  64,  63,  62,
        61,  60,  59,  58,  57,  56,  55,  54,  53,  52,  51,  50,  49,
        48,  47,  46,  45,  44,  43,  42,  41,  40,  39,  38,  37,  36,
        35,  34,  33,  32,  31,  30,  29,  28,  27,  26,  25,  24,  23,
        22,  21,  20,  19,  18,  17,  16,  15,  14,  13,  12,  11,  10,
         9,   8,   7,   6,   5,   4,   3,   2])

In [19]:
# linspace is a way to create an array of equally spaced values
# over a specified range
# linspace is inclusive of the last value

vals = np.linspace(0,100,25)  # (lower, upper, number of steps)
vals

array([   0.        ,    4.16666667,    8.33333333,   12.5       ,
         16.66666667,   20.83333333,   25.        ,   29.16666667,
         33.33333333,   37.5       ,   41.66666667,   45.83333333,
         50.        ,   54.16666667,   58.33333333,   62.5       ,
         66.66666667,   70.83333333,   75.        ,   79.16666667,
         83.33333333,   87.5       ,   91.66666667,   95.83333333,  100.        ])

In [20]:
# define an array of all the evens from 2 to 50
evens = np.linspace(2,50,25)
evens

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.])