### EXERCISES

1. Using one of the methods from np.random create an array of size 4,4 with random numbers from 0-100. You can have these numbers be ints or floats. 
    * Find the standard deviation. Find the variance. Find the mean.  
    * Define an array that has the sum for each column.
    * Define an array that is the product of the elements of the previous array.

2. Practice using indexing for numpy arrays. 
    * Print the first row of the original (4,4) array.
    * Print the last element of the third row.
    * Print the second column. 
    * (Optional) Define an array for each column of the array. Use the np.hstack command to put all the columns back together and get the original matrix.

In [10]:
import numpy as np

#### 1. Using one of the methods from np.random create an array of size 4,4 with random numbers from 0-100. You can have these numbers be ints or floats. 

In [11]:
ran_array = np.random.randint(1,100, size = (4,4)) #chooses a set of numbers to arrange in the specified array size
ran_array

array([[29, 12, 88, 76],
       [ 7, 65, 55, 38],
       [58, 86, 77, 38],
       [25, 85, 92,  6]])

In [12]:
print('Standard Deviation of array is',np.std(ran_array))
#calculates the standard deviation of the given array
print('Variance of array is', np.var(ran_array))
#calculates the variance of the given array
print('Mean of array is',np.mean(ran_array))
#calculates the mean/average of the given array

Standard Deviation of array is 29.522700482
Variance of array is 871.58984375
Mean of array is 52.3125


In [13]:
colu_sum = np.sum(ran_array, axis = 0) #axis = 0 adds the columns to an array
print(ran_array)                       #axis = 1 adds the rows
colu_sum

[[29 12 88 76]
 [ 7 65 55 38]
 [58 86 77 38]
 [25 85 92  6]]


array([119, 248, 312, 158])

#### 2. Practice using indexing for numpy arrays. 

Print the first row of the original (4,4) array.

In [14]:
print(ran_array[0]) #prints the first row of the array

[29 12 88 76]


Print the last element of the third row.

In [15]:
print(ran_array[-2][-1]) # The -2 represents the 3rd row or the 2nd to the last
# The -1 represent which elements to print, the last

38


Print the second column. 

In [32]:
ran_array[:,1:2] #prints out the first column, replace the ran_array with your defined array

array([[12],
       [65],
       [86],
       [85]])

#### FINANCE APPLICATIONS
$$ CashFlow = Income - Expenses $$
1. Create a function that computes the cash flow when given values for income and expenses. Make sure to return the cash flow at the end of the function.

    * Test the function with some values
    
2. Create a 1d array of 50 random values between 1-20 for Income and an array for Expenses.

    * Define an object called Cash Flow that is equal to the result of passing these arrays through your function
    * Use np.argmax/min and np.max/min to determine the maximum and minimum Cash Flows from the set from these random values.
    * Next, use np.sum to sum both the incomes and the expenses. Then, again use the function to calculate the total cash flow.

#### 1.) Create a function that computes the cash flow when given values for income and expenses. Make sure to return the cash flow at the end of the function.

In [17]:
def calc_cash(i,e):#defines function with the values to be given (i and v)
    fl = i - e #given function
    return fl

### Test the function with some values

In [18]:
calc_cash(2,1) #inputs values for i and e

1

### 2.) Create a 1d array of 50 random values between 1-20 for Income and an array for Expenses

In [31]:
inc_array = np.random.randint(1,20, size=50) #chooses values from 1-20 and makes an array of 50 values
print(inc_array)  #size defines the amount of values in the array
exp_array = np.random.randint(1,20, size=50)
print(exp_array)

[ 2 15  7  3 14 17 19  3  1 18  9  7 15 11  8 18  7  1  9 13 14  4 14  1 12
  8  1 16 13 12 11  2 19  7  4  9  4  8  2 11  1  2  8  6  4 14 14 15 12  1]
[17 15  6 11  4 13 18  5 14 12 19 10  4  6  4 13  3  8 13 15 15 12 18  7  4
 17 13  3  1  8  7  8 13 10  7 17 12  3  2  1 15 14 19  9 17  6 18  7 10 16]


### B.) Define an object called Cash Flow that is equal to the result of passing these arrays through your function

In [42]:
cash_flow = calc_cash(inc_array,exp_array) #instead of i and e, it uses the previously defined arrays 
print(cash_flow)

[-15   0   1  -8  10   4   1  -2 -13   6 -10  -3  11   5   4   5   4  -7
  -4  -2  -1  -8  -4  -6   8  -9 -12  13  12   4   4  -6   6  -3  -3  -8
  -8   5   0  10 -14 -12 -11  -3 -13   8  -4   8   2 -15]


### C.) Use np.argmax/min and np.max/min to determine the maximum and minimum Cash Flows from the set from these random values.

In [27]:
print(np.argmax(cash_flow)) #finds the maximum value in the previous array
np.argmin(cash_flow) #finds the smallest value in the previous array

3


13

### D.) Next, use np.sum to sum both the incomes and the expenses. Then, again use the function to calculate the total cash flow.

In [40]:
a = np.sum(inc_array, axis=0) #adds up all the values in the inc_array
b = np.sum(exp_array, axis=0) #adds up all the values in the exp_array
calc_cash(a,b) #uses the defined values to calculate cash flow

-73