### EXERCISES

1. Use np.linspace to create an array of angles from 0 to 2$\pi$. 
    * Use the np.sin command on the array. Do the same for np.cos and np.tan. 
    * Convert the array of angles from radians to degrees. 
    
2. Create a 2 by 2 array of random integers. 
    * Transpose the matrix.
    * Find the determinant of the matrix. 
    * Find the inverse of the matrix.
    * Find the eigenvalues and eigenvectors of the matrix.
    
3. Use an array you already have or create a new one and save it as a csv file. Use ls to check the file was saved to the current 
#### PHYSICS PROBLEMS

PROJECTILE MOTION

A ball is launched from ground level at 10 m/s and an angle of 45 degrees. The acceleration due to gravity is -9.8 m/s$^2$ and air resistance can be neglected. 

1. Find the components of the launch velocity:
    * What is the velocity in the upward direction? Define this as  v_y.
    * What is the velocity in the horizontal direction? Define this as v_x. 
    * Determine the time of flight for the ball.
    * Determine the maximum height of the ball.
    * Determine the range of the ball.
    
2. Define a function our a few functions that solves the problem above. 

3. Now, define an array of launch velocities and pass through the function for a given angle. 

4. Do the same but for an array of angles for a given launch velocity.

5. Can you change the function with a for loop to loop through 5 different angles with 10 different launch velocities?

#### 1A.) Use np.linspace to create an array of angles from 0 to 2$\pi$.

In [15]:
import numpy as np
pi = np.pi #redifined np.pi as pi 
sin = np.sin
cos = np.cos
tan = np.tan

In [14]:
pepe = np.linspace(0,2*pi,25) #creates array from 0 to 2*pi
pepe

array([ 0.        ,  0.26179939,  0.52359878,  0.78539816,  1.04719755,
        1.30899694,  1.57079633,  1.83259571,  2.0943951 ,  2.35619449,
        2.61799388,  2.87979327,  3.14159265,  3.40339204,  3.66519143,
        3.92699082,  4.1887902 ,  4.45058959,  4.71238898,  4.97418837,
        5.23598776,  5.49778714,  5.75958653,  6.02138592,  6.28318531])

#### 1B.) Use the np.sin command on the array. Do the same for np.cos and np.tan.  

In [23]:
print('Sin of array =',sin(pepe)) #uses redefined numpy operations to calculate sine of array

Sin of array = [  0.00000000e+00   2.58819045e-01   5.00000000e-01   7.07106781e-01
   8.66025404e-01   9.65925826e-01   1.00000000e+00   9.65925826e-01
   8.66025404e-01   7.07106781e-01   5.00000000e-01   2.58819045e-01
   1.22464680e-16  -2.58819045e-01  -5.00000000e-01  -7.07106781e-01
  -8.66025404e-01  -9.65925826e-01  -1.00000000e+00  -9.65925826e-01
  -8.66025404e-01  -7.07106781e-01  -5.00000000e-01  -2.58819045e-01
  -2.44929360e-16]


In [22]:
print('Cosine of array =',cos(pepe)) #uses redefined numpy operations to calculate cosine of array

Cosine of array = [  1.00000000e+00   9.65925826e-01   8.66025404e-01   7.07106781e-01
   5.00000000e-01   2.58819045e-01   6.12323400e-17  -2.58819045e-01
  -5.00000000e-01  -7.07106781e-01  -8.66025404e-01  -9.65925826e-01
  -1.00000000e+00  -9.65925826e-01  -8.66025404e-01  -7.07106781e-01
  -5.00000000e-01  -2.58819045e-01  -1.83697020e-16   2.58819045e-01
   5.00000000e-01   7.07106781e-01   8.66025404e-01   9.65925826e-01
   1.00000000e+00]


In [24]:
print('Tangent of array =', tan(pepe)) #uses redefined numpy operations to calculate tangent of array

Tangent of array = [  0.00000000e+00   2.67949192e-01   5.77350269e-01   1.00000000e+00
   1.73205081e+00   3.73205081e+00   1.63312394e+16  -3.73205081e+00
  -1.73205081e+00  -1.00000000e+00  -5.77350269e-01  -2.67949192e-01
  -1.22464680e-16   2.67949192e-01   5.77350269e-01   1.00000000e+00
   1.73205081e+00   3.73205081e+00   5.44374645e+15  -3.73205081e+00
  -1.73205081e+00  -1.00000000e+00  -5.77350269e-01  -2.67949192e-01
  -2.44929360e-16]


#### 1C.) Convert the array of angles from radians to degrees. 

In [27]:
print(np.degrees(pepe))

[   0.   15.   30.   45.   60.   75.   90.  105.  120.  135.  150.  165.
  180.  195.  210.  225.  240.  255.  270.  285.  300.  315.  330.  345.
  360.]


#### 2A.) Create a 2 x 2 array of random integers

In [30]:
rand_array = np.random.randint(1,20, size = (2,2))
rand_array

array([[14, 17],
       [10, 11]])

#### 2B.)Transpose the matrix.

In [43]:
pepe1 = rand_array.T #Transposes the previous matrix
print(pepe1)

[[14 10]
 [17 11]]


#### Find the determinant of the matrix. 

In [35]:
pepe2 = np.linalg.det(rand_array) #calculates the determinant of the previous matrix
print('Determinant of the matrix =',pepe2)

-15.999999999999963

#### Find the inverse of the matrix.

In [41]:
pepe3 = np.linalg.inv(rand_array) #calculates the inverse of the previous matrix
print('Inverse of matrix =', pepe3)

Inverse of matrix = [[-0.6875  1.0625]
 [ 0.625  -0.875 ]]


#### Find the eigenvalues and eigenvectors of the matrix.

In [42]:
pepe4 = np.linalg.eig(rand_array) #calculates eigenvalues and eigenvectors of the previous matrix
print('Eigenvalues/vectors of matrix =', pepe4)

Eigenvalues/vectors of matrix = (array([ 25.62440475,  -0.62440475]), array([[ 0.82546958, -0.75808808],
       [ 0.56444661,  0.65215217]]))


#### 3. Use an array you already have or create a new one and save it as a csv file. Use ls to check the file was saved to the current 

In [48]:
# Random array to be saves as a datafile
ricardo_milos = np.random.randint(0,20,size = (5,5))
ricardo_milos

array([[ 9,  5, 19, 14, 10],
       [ 4, 17,  8,  4, 16],
       [ 7,  4, 12, 17,  1],
       [19,  2, 19, 11,  7],
       [12, 18,  8,  7, 11]])

In [49]:
np.savetxt("ricardo.csv",ricardo_milos,delimiter=",") #saves the new array as a csv file

In [50]:
%ls #displays all files in the directory

Brian_1D_ProjMotion.ipynb  Brian_NumPy_Ex_1.ipynb         ricardo.csv
Brian_Exercises_1.ipynb    Brian_NumPy_Ex_2.ipynb         toss_rock_up_01.jpg
Brian_Exercises_2.ipynb    Brian_Plotting_Activity.ipynb  toss_rock_up_02.jpg
Brian_Exercises_3.ipynb    NumPy_Ex_3.ipynb
Brian_Exercises_4.ipynb    Practice_Lists.ipynb


###### 'It is not until a mosquito lands on your testicles that you learn there is always a way to solve problems without violence -Confucious'

###### 'As I nodded, nearly napping, suddenly there came a clapping, as of ass cheeks gently clapping, clapping at my bedroom door. "Tis a visitor" I muttered. dummy thicc, and nothing more -Shakespeares dummy thicc ass'